[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
gas_reports = ["DocumentRegistry"]

remappings = [
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 10 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
